language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - PEEWEE_TEST_BACKEND=sqlite
  - PEEWEE_TEST_BACKEND=postgresql
  - PEEWEE_TEST_BACKEND=mysql
services:
  - postgres
  - mysql
install: "pip install psycopg2 Cython pymysql"
before_script:
  - sh -c "if [ '$PEEWEE_TEST_BACKEND' = 'postgresql' ]; then psql -c 'drop database if exists peewee_test;' -U postgres; fi"
  - sh -c "if [ '$PEEWEE_TEST_BACKEND' = 'postgresql' ]; then psql -c 'create database peewee_test;' -U postgres; fi"
  - sh -c "if [ '$PEEWEE_TEST_BACKEND' = 'postgresql' ]; then psql peewee_test -c 'create extension hstore;' -U postgres; fi"
  - sh -c "if [ '$PEEWEE_TEST_BACKEND' = 'mysql' ]; then mysql -e 'create database if not exists peewee_test;'; fi"
script: "python runtests.py -a"
