language: python
cache: pip
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
  env:
    - PEEWEE_TEST_BACKEND=sqlite
    - PEEWEE_TEST_BACKEND=postgresql
    - PEEWEE_TEST_BACKEND=mysql
addons:
  postgresql: "9.6"
  mariadb: "10.3"
services:
  - postgresql
  - mariadb
install: "pip install psycopg2-binary Cython pymysql apsw mysql-connector"
before_script:
  - python setup.py build_ext -i
  - psql -c 'drop database if exists peewee_test;' -U postgres
  - psql -c 'create database peewee_test;' -U postgres
  - psql peewee_test -c 'create extension hstore;' -U postgres
  - mysql -e 'drop database if exists peewee_test;'
  - mysql -e 'create database peewee_test;'
  - mysql -e 'grant all on *.* to travis@localhost;'
script: "python runtests.py"
